"options":
  "ssh-hostname":
    "type": "string"
    "default": ""
    "description": "The hostname or IP address of the machine to"
  "ssh-username":
    "type": "string"
    "default": ""
    "description": "The username to login as."
  "ssh-password":
    "type": "string"
    "default": ""
    "description": "The password used to authenticate."
  "ssh-private-key":
    "type": "string"
    "default": ""
    "description": "DEPRECATED. The private ssh key to be used to authenticate."
  "ssh-public-key":
    "type": "string"
    "default": ""
    "description": "The public key of this unit."
  "ssh-key-type":
    "type": "string"
    "default": "rsa"
    "description": "The type of encryption to use for the SSH key."
  "ssh-key-bits":
    "type": "int"
    "default": !!int "4096"
    "description": "The number of bits to use for the SSH key."
  "mtd-mode":
    "type": "int"
    "default": !!int "3"
    "description": "MTD operation mode."
  "mtd-secret":
    "type": "string"
    "default": "c3VwZXJzZWNyZXQ="
    "description": "MTD secret key."
  "mtd-interval":
    "type": "int"
    "default": !!int "30"
    "description": "MTD mutation interval in milliseconds."
  "mtd-offset":
    "type": "int"
    "default": !!int "0"
    "description": "MTD mutation offset in milliseconds."
  "mtd-real-port":
    "type": "int"
    "default": !!int "51820"
    "description": "Service port."
