additionalParamsForVnf:
- member-vnf-index: "1"
  additionalParams:
    tunnel_address: "10.100.100.1/24"
    tunnel_id: "test"
    vsi_id: "10"
    use_data_interfaces: "false"
- member-vnf-index: "2"
  additionalParams:
    mtd_mode: "3"